language: c
sudo: required
services:
  - docker
env:
  global:
    # QUAY_USERNAME
    - secure: "qfdMOibFw3I3/l7EnotFajkGtWlZ9P8J4MRNgeh9eQE1sGQx5681kLUoif5M611Lm3LseknTpz5oXDiyapLHhueR6Yzx//d2N/CIkSkFxpQ6Skz7aDwsbtDfPTx2oawQtpUFcEcHwJWl8nZFGtU/l+fKsOW4xrTn5P5VN3sNKPbw+gMwtgLODWK/HnCkUxXYlJDFDlaGl4lVOUe3buZ6KXUf2JojzJrn/7vZ5zYf0go7iRfzSDYw8dWVhuvTMGLLhtdCwsfX6+VyNXrlMImXst+6NIGmV+LIXSmJfjncf3cE/33VQR/jmUsQH7Lep8DRuUcfLiCH/NKHnGoZ6NH0D9VvPpt6F5v5ej9KuvRqlA9qNW7mOTLMHDG06yvqf6NLv/DwGYvtgE2w2D7LqN2OvryATQQhyaEJaQcILtbw5E1El2YIOKcc2izL+y4dvogxtMftbKT+i3EqF/LpbbzIZv81bgMWXAVeevbfudeBjKMPDd9jd7Gvt11Iouo0Pz0oM1qPKIyWxU3ltDRZjU7KZpdtZDmQ0zyvDooaRuzG+o8jiawDGBM8SCBcQFnbKqcjxR/dA+iDfs9em83Tej2pMkzPyQagZUTEvVxPzh7jaAvZtBfWX9BaxCOYd5F03QoNaCN+rmXjVsCQjQqQ0bqzBkmUwl25VZwmMVMs1ZNTTFM="
    # QUAY_PASSWORD
    - secure: "lE9Yeh1+TdnKy+ghxfxMZQ4y9E04/BDUhHH0csxYA2xbrWWu2UWc1X0XsU1uDP3/DTyMn3SJv0yCfD1AP86a350yXd7Z40PqBvk59HAoSCC9BXT9w/DfWeMg1DbYrqKyFyvd7xFQvlkIakf8a1CU9C/fSLFBhWPiByAaglYqr09cCeX0zuNtliney6P4Ncl+qcUH0mQ2JS6EUCauH1wsg+w7tyLmTjQSuUCqYgVkcuyPXBLRbNLinZ6NT644GWy79dWv2eKVGbJTLX1a5WvSx0aDgkubAPHTvTlo4Z6iEeKB968VdPo+K/7rwL5wbD+0n/b6JRdXPS7Q/rE6bmrcTIX1GrOwmgQnDjawL6OkpXL59MUlNzUcFeuE6y26B2sGuoFjmnqKOCxcwnAV2SviloSjRc9+F4HYJS2Ad9L737yl3YWnKlQSvh9JUwmEkdaQtefwe7bxkDpXQpHd5XhdSBeVWqn5QheTzV7dKykzFrpf3Hd4A8yZ7IRlFJhQR5wPILKpZY86frA2Vn4vYOCw1uJHceZu3gD7/oRWTup5CfKeB4hLNj+UyC/NZ0Pa+1sIb8rNCYflHZDEuxoNLs3UgGDgfLatiY8CIbhUCFg2QdZJ9kacf/YyyncRKCf0pHDUrgk+5p2qCrHNt4hvCdIQih7O90PJkdSJr7WdmZu8vow="
script:
  - ./scripts/build.sh
after_success:
  - ./scripts/deploy.sh
