language: c
sudo: required
dist: trusty
services:
  - docker
env:
  global:
    # QUAY_USERNAME
    - secure: "LfCuuhyKH6V2XnWn2Mvl1FdC/tjFFnsmFpN8aqFLFK8SCgf+0PrmWdy4M1LxiuLez2SdCj6fCdi7RaJDllaTKiwGuc45kJG/o9I6ekXfB4fq4hbjzhMcjiamG691ObFKanS4zFqT/AehVPQclKjzo7zYpvAs9B5bve2aWjLLTJWNSfN2SMsx6Hs2RE/fd5iwSKIx/JRTTECLAoWK0r+eD+hGum+y6pp1FV9GaUXBrpmiM5cYJwsufJJvosoh3xCwtR5S+ZjJRBzP8sZg5FdGWaGolQxwxKJjl7az/2NJPpbImhHA+MJxmfVBnLroQAtqGKTiScKPq0W+Mk+k/3mtmA/aHz2rDvE+oC0RzGIsEUWZWKylJ3OLTQSfHKQcZrSrZRqdVIOpX3ZYmvhrdMlYHcw7jaNuhJcha14kCgoLszZVfGwAPFXN9qAyqhfacGLtIwg4uN1t3sq3k3rj3uTeg33yqQu5xUN4fu898N3cC0nl5MtrROnAbFs94Adc+1pzUBZ85ybK/iJaor82ycj8S0VDDpRcv3coqm8z3FLR/uinV3DFjIRCPbcPYxJEdTiryIedWNiRaoNZoPeUzTLXyt12x4ENiAUt/AfuRLAMUwbdO0NlaeWQaXDRD2yAeC6b7SMFC5TjX/irP3PF7Bq2zZwliMqUZ1QIQ8nZO96uQOI="
    # QUAY_PASSWORD
    - secure: "XTwHK37uVitVWfORScvCivCtAfccrcqyCMYGkmO1EUSPvC/oHTm5TUPGb6MonlAUc+nXWu/+Aj2TVe5SpwO+4CAXZkbXzr+Iwm4gdUvVX21dPz1+K9ay5Ve6dIXTtJSJZSXQYoO0SYVX2M4RnzrsXOdVgBmPjGToj6e5v5t5IF81VcSCkXGJK8DfiRu7xRL1OhXZbEFMXHYGrVyGRl5Q61CjLPUkHrKnWQawTWlDaQlVJw1Ay+BWrnHmLiFN4V6mTugLR0fa/tFSzTXcRzRVAleTRqt/six1XVW3mJxlAzSKhvRDNOkdQyC4Y7yyGq6Zu/zolVOnmgtuHlcmP1iQOKSla6hTpywLOVRzxvmTkC3V9e5OsSwOJs9/CY51yGCK26pKNtuL4QtyOAxuKn7Px+f/hVy2e7xg6Kf3aw49aZVxqZGh9+AauGxnohAvMGJ/5vkq4T9yDKdjR6e3nftuMsdnfPryjF9BbwdAY83kki9qJq/XTNofVYpfH6ihrii7lI7ifzspIdt6d8/NIwfg2eoJvupsTMi3DyGnhy4QJbHyOQ8YZ4Xz2H9WvUnUnbWGd3MKds4Wu78jMO62O/XBDhxq6lKZQThKNaFU7btm5Roorkhpku+88KGT1pOPDeHbne+5LQ2Qv6YIRetUGZV9+cR8b5FWAK1ZtzyyFuPojo4="
script:
  - ./scripts/build.sh
after_success:
  - ./scripts/deploy.sh
