#!/bin/bash
set -eo pipefail

if [[ -f /etc/environment_proxy ]]; then
    source /etc/environment_proxy
fi

## Load bundle from Bind Mount, URL or STDIN

export HOME=/app
mkdir -p $HOME

if [[ $(ls -A $HOME) ]]; then
    true
elif [[ $BUNDLE_URL ]]; then
    bundle-fetch "$BUNDLE_URL" | tar -xzC $HOME
    unset BUNDLE_URL
else
    cat | tar -xzC $HOME
fi
cd $HOME

## Load profile.d

shopt -s nullglob
mkdir -p .profile.d
for file in .profile.d/*; do
    source $file
done
hash -r

case "$1" in
    start)
        if [[ -f Procfile ]]; then
            command="$(ruby -e "require 'yaml';puts YAML.load_file('Procfile')['$2']")"
        else
            command="$(ruby -e "require 'yaml';puts (YAML.load_file('.release')['default_process_types'] || {})['$2']")"
        fi
        ;;
    *)
        command="$@"
        ;;
esac

## Run! (if we can)

if [[ "$command" ]]; then
    exec bash -c "$command"
else
    echo "$2 not found in Procfile"
    exit 1
fi
